services:
  - type: web
    name: rag-ai-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: UPSTASH_REDIS_TOKEN
        sync: false
